version: '3.8'

services:
  mysql:
    image: mysql/mysql-server:latest
    container_name: mysql
    env_file:
      - .env
    ports:
      - 3306:3306
  user-service:
    build: ./
    container_name: user-service
    env_file:
      - .env
    ports:
      - 5000:5000
    volumes:
      - ./:/app
    depends_on:
      - mysql
