version: '3.8'

services:
  mysql:
    image: mysql:8.1
    container_name: mysql-user-service
    env_file:
      - .env

  user-service:
    build: ./
    container_name: user-service
    env_file:
      - .env
    ports:
      - ${USER_SERVICE_PORT}:${USER_SERVICE_PORT}
      # - 127.0.0.1:5000:${USER_SERVICE_PORT}
    depends_on:
      - mysql
    volumes:
      - ./src:/app/src
    command: npm run start:dev
    networks:
      - default
      - humf-service-network

  # Development
  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myadmin
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql

networks:
  humf-service-network:
    name: humf-service-network
  #   external: true