version: '3.8'

services:
  mysql:
    image: mysql
    container_name: mysql
    env_file:
      - .env
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 60s
      retries: 10
    
  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myadmin
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql

  # user-service:
  #   build: ./
  #   container_name: user-service
  #   env_file:
  #     - .env
  #   ports:
  #     - 5000:5000
  #   depends_on:
  #     mysql:
  #       condition: service_healthy